/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as RedeRouteImport } from './routes/rede'
import { Route as PlanejadorRouteImport } from './routes/planejador'
import { Route as MidiaRouteImport } from './routes/midia'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PontoSlugRouteImport } from './routes/ponto.$slug'
import { Route as DashboardPedidosRouteImport } from './routes/dashboard.pedidos'
import { Route as DashboardMidiasRouteImport } from './routes/dashboard.midias'
import { Route as DashboardCampanhasRouteImport } from './routes/dashboard.campanhas'
import { Route as DashboardCalendarioRouteImport } from './routes/dashboard.calendario'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminPrecosRouteImport } from './routes/admin.precos'
import { Route as AdminModeracaoRouteImport } from './routes/admin.moderacao'
import { Route as AdminInventarioRouteImport } from './routes/admin.inventario'
import { Route as AdminHorariosRouteImport } from './routes/admin.horarios'
import { Route as AdminFormatosRouteImport } from './routes/admin.formatos'
import { Route as AdminCampanhasRouteImport } from './routes/admin.campanhas'
import { Route as AdminBloqueiosRouteImport } from './routes/admin.bloqueios'
import { Route as DashboardPedidosIndexRouteImport } from './routes/dashboard.pedidos.index'
import { Route as DashboardCampanhasIndexRouteImport } from './routes/dashboard.campanhas.index'
import { Route as AdminInventarioIndexRouteImport } from './routes/admin.inventario.index'
import { Route as AdminCampanhasIndexRouteImport } from './routes/admin.campanhas.index'
import { Route as DashboardPedidosIdRouteImport } from './routes/dashboard.pedidos.$id'
import { Route as DashboardCampanhasNovaRouteImport } from './routes/dashboard.campanhas.nova'
import { Route as AdminInventarioAtivosRouteImport } from './routes/admin.inventario.ativos'
import { Route as AdminCampanhasNovaRouteImport } from './routes/admin.campanhas.nova'
import { Route as DashboardCampanhasNovaIndexRouteImport } from './routes/dashboard.campanhas.nova.index'
import { Route as DashboardCampanhasNovaRevisaoRouteImport } from './routes/dashboard.campanhas.nova.revisao'
import { Route as DashboardCampanhasNovaPontosRouteImport } from './routes/dashboard.campanhas.nova.pontos'
import { Route as DashboardCampanhasNovaHorariosRouteImport } from './routes/dashboard.campanhas.nova.horarios'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeRoute = RedeRouteImport.update({
  id: '/rede',
  path: '/rede',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejadorRoute = PlanejadorRouteImport.update({
  id: '/planejador',
  path: '/planejador',
  getParentRoute: () => rootRouteImport,
} as any)
const MidiaRoute = MidiaRouteImport.update({
  id: '/midia',
  path: '/midia',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PontoSlugRoute = PontoSlugRouteImport.update({
  id: '/ponto/$slug',
  path: '/ponto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPedidosRoute = DashboardPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMidiasRoute = DashboardMidiasRouteImport.update({
  id: '/midias',
  path: '/midias',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampanhasRoute = DashboardCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarioRoute = DashboardCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrecosRoute = AdminPrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModeracaoRoute = AdminModeracaoRouteImport.update({
  id: '/moderacao',
  path: '/moderacao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventarioRoute = AdminInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHorariosRoute = AdminHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormatosRoute = AdminFormatosRouteImport.update({
  id: '/formatos',
  path: '/formatos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampanhasRoute = AdminCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBloqueiosRoute = AdminBloqueiosRouteImport.update({
  id: '/bloqueios',
  path: '/bloqueios',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardPedidosIndexRoute = DashboardPedidosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardPedidosRoute,
} as any)
const DashboardCampanhasIndexRoute = DashboardCampanhasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCampanhasRoute,
} as any)
const AdminInventarioIndexRoute = AdminInventarioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminInventarioRoute,
} as any)
const AdminCampanhasIndexRoute = AdminCampanhasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCampanhasRoute,
} as any)
const DashboardPedidosIdRoute = DashboardPedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardPedidosRoute,
} as any)
const DashboardCampanhasNovaRoute = DashboardCampanhasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => DashboardCampanhasRoute,
} as any)
const AdminInventarioAtivosRoute = AdminInventarioAtivosRouteImport.update({
  id: '/ativos',
  path: '/ativos',
  getParentRoute: () => AdminInventarioRoute,
} as any)
const AdminCampanhasNovaRoute = AdminCampanhasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AdminCampanhasRoute,
} as any)
const DashboardCampanhasNovaIndexRoute =
  DashboardCampanhasNovaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardCampanhasNovaRoute,
  } as any)
const DashboardCampanhasNovaRevisaoRoute =
  DashboardCampanhasNovaRevisaoRouteImport.update({
    id: '/revisao',
    path: '/revisao',
    getParentRoute: () => DashboardCampanhasNovaRoute,
  } as any)
const DashboardCampanhasNovaPontosRoute =
  DashboardCampanhasNovaPontosRouteImport.update({
    id: '/pontos',
    path: '/pontos',
    getParentRoute: () => DashboardCampanhasNovaRoute,
  } as any)
const DashboardCampanhasNovaHorariosRoute =
  DashboardCampanhasNovaHorariosRouteImport.update({
    id: '/horarios',
    path: '/horarios',
    getParentRoute: () => DashboardCampanhasNovaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contato': typeof ContatoRoute
  '/criar-conta': typeof CriarContaRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/galeria': typeof GaleriaRoute
  '/midia': typeof MidiaRoute
  '/planejador': typeof PlanejadorRoute
  '/rede': typeof RedeRoute
  '/sobre': typeof SobreRoute
  '/admin/bloqueios': typeof AdminBloqueiosRoute
  '/admin/campanhas': typeof AdminCampanhasRouteWithChildren
  '/admin/formatos': typeof AdminFormatosRoute
  '/admin/horarios': typeof AdminHorariosRoute
  '/admin/inventario': typeof AdminInventarioRouteWithChildren
  '/admin/moderacao': typeof AdminModeracaoRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/dashboard/calendario': typeof DashboardCalendarioRoute
  '/dashboard/campanhas': typeof DashboardCampanhasRouteWithChildren
  '/dashboard/midias': typeof DashboardMidiasRoute
  '/dashboard/pedidos': typeof DashboardPedidosRouteWithChildren
  '/ponto/$slug': typeof PontoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/campanhas/nova': typeof AdminCampanhasNovaRoute
  '/admin/inventario/ativos': typeof AdminInventarioAtivosRoute
  '/dashboard/campanhas/nova': typeof DashboardCampanhasNovaRouteWithChildren
  '/dashboard/pedidos/$id': typeof DashboardPedidosIdRoute
  '/admin/campanhas/': typeof AdminCampanhasIndexRoute
  '/admin/inventario/': typeof AdminInventarioIndexRoute
  '/dashboard/campanhas/': typeof DashboardCampanhasIndexRoute
  '/dashboard/pedidos/': typeof DashboardPedidosIndexRoute
  '/dashboard/campanhas/nova/horarios': typeof DashboardCampanhasNovaHorariosRoute
  '/dashboard/campanhas/nova/pontos': typeof DashboardCampanhasNovaPontosRoute
  '/dashboard/campanhas/nova/revisao': typeof DashboardCampanhasNovaRevisaoRoute
  '/dashboard/campanhas/nova/': typeof DashboardCampanhasNovaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/galeria': typeof GaleriaRoute
  '/midia': typeof MidiaRoute
  '/planejador': typeof PlanejadorRoute
  '/rede': typeof RedeRoute
  '/sobre': typeof SobreRoute
  '/admin/bloqueios': typeof AdminBloqueiosRoute
  '/admin/formatos': typeof AdminFormatosRoute
  '/admin/horarios': typeof AdminHorariosRoute
  '/admin/moderacao': typeof AdminModeracaoRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/dashboard/calendario': typeof DashboardCalendarioRoute
  '/dashboard/midias': typeof DashboardMidiasRoute
  '/ponto/$slug': typeof PontoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/campanhas/nova': typeof AdminCampanhasNovaRoute
  '/admin/inventario/ativos': typeof AdminInventarioAtivosRoute
  '/dashboard/pedidos/$id': typeof DashboardPedidosIdRoute
  '/admin/campanhas': typeof AdminCampanhasIndexRoute
  '/admin/inventario': typeof AdminInventarioIndexRoute
  '/dashboard/campanhas': typeof DashboardCampanhasIndexRoute
  '/dashboard/pedidos': typeof DashboardPedidosIndexRoute
  '/dashboard/campanhas/nova/horarios': typeof DashboardCampanhasNovaHorariosRoute
  '/dashboard/campanhas/nova/pontos': typeof DashboardCampanhasNovaPontosRoute
  '/dashboard/campanhas/nova/revisao': typeof DashboardCampanhasNovaRevisaoRoute
  '/dashboard/campanhas/nova': typeof DashboardCampanhasNovaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contato': typeof ContatoRoute
  '/criar-conta': typeof CriarContaRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/galeria': typeof GaleriaRoute
  '/midia': typeof MidiaRoute
  '/planejador': typeof PlanejadorRoute
  '/rede': typeof RedeRoute
  '/sobre': typeof SobreRoute
  '/admin/bloqueios': typeof AdminBloqueiosRoute
  '/admin/campanhas': typeof AdminCampanhasRouteWithChildren
  '/admin/formatos': typeof AdminFormatosRoute
  '/admin/horarios': typeof AdminHorariosRoute
  '/admin/inventario': typeof AdminInventarioRouteWithChildren
  '/admin/moderacao': typeof AdminModeracaoRoute
  '/admin/precos': typeof AdminPrecosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/dashboard/calendario': typeof DashboardCalendarioRoute
  '/dashboard/campanhas': typeof DashboardCampanhasRouteWithChildren
  '/dashboard/midias': typeof DashboardMidiasRoute
  '/dashboard/pedidos': typeof DashboardPedidosRouteWithChildren
  '/ponto/$slug': typeof PontoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/campanhas/nova': typeof AdminCampanhasNovaRoute
  '/admin/inventario/ativos': typeof AdminInventarioAtivosRoute
  '/dashboard/campanhas/nova': typeof DashboardCampanhasNovaRouteWithChildren
  '/dashboard/pedidos/$id': typeof DashboardPedidosIdRoute
  '/admin/campanhas/': typeof AdminCampanhasIndexRoute
  '/admin/inventario/': typeof AdminInventarioIndexRoute
  '/dashboard/campanhas/': typeof DashboardCampanhasIndexRoute
  '/dashboard/pedidos/': typeof DashboardPedidosIndexRoute
  '/dashboard/campanhas/nova/horarios': typeof DashboardCampanhasNovaHorariosRoute
  '/dashboard/campanhas/nova/pontos': typeof DashboardCampanhasNovaPontosRoute
  '/dashboard/campanhas/nova/revisao': typeof DashboardCampanhasNovaRevisaoRoute
  '/dashboard/campanhas/nova/': typeof DashboardCampanhasNovaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contato'
    | '/criar-conta'
    | '/dashboard'
    | '/entrar'
    | '/galeria'
    | '/midia'
    | '/planejador'
    | '/rede'
    | '/sobre'
    | '/admin/bloqueios'
    | '/admin/campanhas'
    | '/admin/formatos'
    | '/admin/horarios'
    | '/admin/inventario'
    | '/admin/moderacao'
    | '/admin/precos'
    | '/admin/usuarios'
    | '/dashboard/calendario'
    | '/dashboard/campanhas'
    | '/dashboard/midias'
    | '/dashboard/pedidos'
    | '/ponto/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/admin/campanhas/nova'
    | '/admin/inventario/ativos'
    | '/dashboard/campanhas/nova'
    | '/dashboard/pedidos/$id'
    | '/admin/campanhas/'
    | '/admin/inventario/'
    | '/dashboard/campanhas/'
    | '/dashboard/pedidos/'
    | '/dashboard/campanhas/nova/horarios'
    | '/dashboard/campanhas/nova/pontos'
    | '/dashboard/campanhas/nova/revisao'
    | '/dashboard/campanhas/nova/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/criar-conta'
    | '/entrar'
    | '/galeria'
    | '/midia'
    | '/planejador'
    | '/rede'
    | '/sobre'
    | '/admin/bloqueios'
    | '/admin/formatos'
    | '/admin/horarios'
    | '/admin/moderacao'
    | '/admin/precos'
    | '/admin/usuarios'
    | '/dashboard/calendario'
    | '/dashboard/midias'
    | '/ponto/$slug'
    | '/admin'
    | '/dashboard'
    | '/admin/campanhas/nova'
    | '/admin/inventario/ativos'
    | '/dashboard/pedidos/$id'
    | '/admin/campanhas'
    | '/admin/inventario'
    | '/dashboard/campanhas'
    | '/dashboard/pedidos'
    | '/dashboard/campanhas/nova/horarios'
    | '/dashboard/campanhas/nova/pontos'
    | '/dashboard/campanhas/nova/revisao'
    | '/dashboard/campanhas/nova'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contato'
    | '/criar-conta'
    | '/dashboard'
    | '/entrar'
    | '/galeria'
    | '/midia'
    | '/planejador'
    | '/rede'
    | '/sobre'
    | '/admin/bloqueios'
    | '/admin/campanhas'
    | '/admin/formatos'
    | '/admin/horarios'
    | '/admin/inventario'
    | '/admin/moderacao'
    | '/admin/precos'
    | '/admin/usuarios'
    | '/dashboard/calendario'
    | '/dashboard/campanhas'
    | '/dashboard/midias'
    | '/dashboard/pedidos'
    | '/ponto/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/admin/campanhas/nova'
    | '/admin/inventario/ativos'
    | '/dashboard/campanhas/nova'
    | '/dashboard/pedidos/$id'
    | '/admin/campanhas/'
    | '/admin/inventario/'
    | '/dashboard/campanhas/'
    | '/dashboard/pedidos/'
    | '/dashboard/campanhas/nova/horarios'
    | '/dashboard/campanhas/nova/pontos'
    | '/dashboard/campanhas/nova/revisao'
    | '/dashboard/campanhas/nova/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  CriarContaRoute: typeof CriarContaRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  GaleriaRoute: typeof GaleriaRoute
  MidiaRoute: typeof MidiaRoute
  PlanejadorRoute: typeof PlanejadorRoute
  RedeRoute: typeof RedeRoute
  SobreRoute: typeof SobreRoute
  PontoSlugRoute: typeof PontoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rede': {
      id: '/rede'
      path: '/rede'
      fullPath: '/rede'
      preLoaderRoute: typeof RedeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejador': {
      id: '/planejador'
      path: '/planejador'
      fullPath: '/planejador'
      preLoaderRoute: typeof PlanejadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midia': {
      id: '/midia'
      path: '/midia'
      fullPath: '/midia'
      preLoaderRoute: typeof MidiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ponto/$slug': {
      id: '/ponto/$slug'
      path: '/ponto/$slug'
      fullPath: '/ponto/$slug'
      preLoaderRoute: typeof PontoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pedidos': {
      id: '/dashboard/pedidos'
      path: '/pedidos'
      fullPath: '/dashboard/pedidos'
      preLoaderRoute: typeof DashboardPedidosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/midias': {
      id: '/dashboard/midias'
      path: '/midias'
      fullPath: '/dashboard/midias'
      preLoaderRoute: typeof DashboardMidiasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campanhas': {
      id: '/dashboard/campanhas'
      path: '/campanhas'
      fullPath: '/dashboard/campanhas'
      preLoaderRoute: typeof DashboardCampanhasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendario': {
      id: '/dashboard/calendario'
      path: '/calendario'
      fullPath: '/dashboard/calendario'
      preLoaderRoute: typeof DashboardCalendarioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/precos': {
      id: '/admin/precos'
      path: '/precos'
      fullPath: '/admin/precos'
      preLoaderRoute: typeof AdminPrecosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderacao': {
      id: '/admin/moderacao'
      path: '/moderacao'
      fullPath: '/admin/moderacao'
      preLoaderRoute: typeof AdminModeracaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventario': {
      id: '/admin/inventario'
      path: '/inventario'
      fullPath: '/admin/inventario'
      preLoaderRoute: typeof AdminInventarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/horarios': {
      id: '/admin/horarios'
      path: '/horarios'
      fullPath: '/admin/horarios'
      preLoaderRoute: typeof AdminHorariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/formatos': {
      id: '/admin/formatos'
      path: '/formatos'
      fullPath: '/admin/formatos'
      preLoaderRoute: typeof AdminFormatosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campanhas': {
      id: '/admin/campanhas'
      path: '/campanhas'
      fullPath: '/admin/campanhas'
      preLoaderRoute: typeof AdminCampanhasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bloqueios': {
      id: '/admin/bloqueios'
      path: '/bloqueios'
      fullPath: '/admin/bloqueios'
      preLoaderRoute: typeof AdminBloqueiosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/pedidos/': {
      id: '/dashboard/pedidos/'
      path: '/'
      fullPath: '/dashboard/pedidos/'
      preLoaderRoute: typeof DashboardPedidosIndexRouteImport
      parentRoute: typeof DashboardPedidosRoute
    }
    '/dashboard/campanhas/': {
      id: '/dashboard/campanhas/'
      path: '/'
      fullPath: '/dashboard/campanhas/'
      preLoaderRoute: typeof DashboardCampanhasIndexRouteImport
      parentRoute: typeof DashboardCampanhasRoute
    }
    '/admin/inventario/': {
      id: '/admin/inventario/'
      path: '/'
      fullPath: '/admin/inventario/'
      preLoaderRoute: typeof AdminInventarioIndexRouteImport
      parentRoute: typeof AdminInventarioRoute
    }
    '/admin/campanhas/': {
      id: '/admin/campanhas/'
      path: '/'
      fullPath: '/admin/campanhas/'
      preLoaderRoute: typeof AdminCampanhasIndexRouteImport
      parentRoute: typeof AdminCampanhasRoute
    }
    '/dashboard/pedidos/$id': {
      id: '/dashboard/pedidos/$id'
      path: '/$id'
      fullPath: '/dashboard/pedidos/$id'
      preLoaderRoute: typeof DashboardPedidosIdRouteImport
      parentRoute: typeof DashboardPedidosRoute
    }
    '/dashboard/campanhas/nova': {
      id: '/dashboard/campanhas/nova'
      path: '/nova'
      fullPath: '/dashboard/campanhas/nova'
      preLoaderRoute: typeof DashboardCampanhasNovaRouteImport
      parentRoute: typeof DashboardCampanhasRoute
    }
    '/admin/inventario/ativos': {
      id: '/admin/inventario/ativos'
      path: '/ativos'
      fullPath: '/admin/inventario/ativos'
      preLoaderRoute: typeof AdminInventarioAtivosRouteImport
      parentRoute: typeof AdminInventarioRoute
    }
    '/admin/campanhas/nova': {
      id: '/admin/campanhas/nova'
      path: '/nova'
      fullPath: '/admin/campanhas/nova'
      preLoaderRoute: typeof AdminCampanhasNovaRouteImport
      parentRoute: typeof AdminCampanhasRoute
    }
    '/dashboard/campanhas/nova/': {
      id: '/dashboard/campanhas/nova/'
      path: '/'
      fullPath: '/dashboard/campanhas/nova/'
      preLoaderRoute: typeof DashboardCampanhasNovaIndexRouteImport
      parentRoute: typeof DashboardCampanhasNovaRoute
    }
    '/dashboard/campanhas/nova/revisao': {
      id: '/dashboard/campanhas/nova/revisao'
      path: '/revisao'
      fullPath: '/dashboard/campanhas/nova/revisao'
      preLoaderRoute: typeof DashboardCampanhasNovaRevisaoRouteImport
      parentRoute: typeof DashboardCampanhasNovaRoute
    }
    '/dashboard/campanhas/nova/pontos': {
      id: '/dashboard/campanhas/nova/pontos'
      path: '/pontos'
      fullPath: '/dashboard/campanhas/nova/pontos'
      preLoaderRoute: typeof DashboardCampanhasNovaPontosRouteImport
      parentRoute: typeof DashboardCampanhasNovaRoute
    }
    '/dashboard/campanhas/nova/horarios': {
      id: '/dashboard/campanhas/nova/horarios'
      path: '/horarios'
      fullPath: '/dashboard/campanhas/nova/horarios'
      preLoaderRoute: typeof DashboardCampanhasNovaHorariosRouteImport
      parentRoute: typeof DashboardCampanhasNovaRoute
    }
  }
}

interface AdminCampanhasRouteChildren {
  AdminCampanhasNovaRoute: typeof AdminCampanhasNovaRoute
  AdminCampanhasIndexRoute: typeof AdminCampanhasIndexRoute
}

const AdminCampanhasRouteChildren: AdminCampanhasRouteChildren = {
  AdminCampanhasNovaRoute: AdminCampanhasNovaRoute,
  AdminCampanhasIndexRoute: AdminCampanhasIndexRoute,
}

const AdminCampanhasRouteWithChildren = AdminCampanhasRoute._addFileChildren(
  AdminCampanhasRouteChildren,
)

interface AdminInventarioRouteChildren {
  AdminInventarioAtivosRoute: typeof AdminInventarioAtivosRoute
  AdminInventarioIndexRoute: typeof AdminInventarioIndexRoute
}

const AdminInventarioRouteChildren: AdminInventarioRouteChildren = {
  AdminInventarioAtivosRoute: AdminInventarioAtivosRoute,
  AdminInventarioIndexRoute: AdminInventarioIndexRoute,
}

const AdminInventarioRouteWithChildren = AdminInventarioRoute._addFileChildren(
  AdminInventarioRouteChildren,
)

interface AdminRouteChildren {
  AdminBloqueiosRoute: typeof AdminBloqueiosRoute
  AdminCampanhasRoute: typeof AdminCampanhasRouteWithChildren
  AdminFormatosRoute: typeof AdminFormatosRoute
  AdminHorariosRoute: typeof AdminHorariosRoute
  AdminInventarioRoute: typeof AdminInventarioRouteWithChildren
  AdminModeracaoRoute: typeof AdminModeracaoRoute
  AdminPrecosRoute: typeof AdminPrecosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBloqueiosRoute: AdminBloqueiosRoute,
  AdminCampanhasRoute: AdminCampanhasRouteWithChildren,
  AdminFormatosRoute: AdminFormatosRoute,
  AdminHorariosRoute: AdminHorariosRoute,
  AdminInventarioRoute: AdminInventarioRouteWithChildren,
  AdminModeracaoRoute: AdminModeracaoRoute,
  AdminPrecosRoute: AdminPrecosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardCampanhasNovaRouteChildren {
  DashboardCampanhasNovaHorariosRoute: typeof DashboardCampanhasNovaHorariosRoute
  DashboardCampanhasNovaPontosRoute: typeof DashboardCampanhasNovaPontosRoute
  DashboardCampanhasNovaRevisaoRoute: typeof DashboardCampanhasNovaRevisaoRoute
  DashboardCampanhasNovaIndexRoute: typeof DashboardCampanhasNovaIndexRoute
}

const DashboardCampanhasNovaRouteChildren: DashboardCampanhasNovaRouteChildren =
  {
    DashboardCampanhasNovaHorariosRoute: DashboardCampanhasNovaHorariosRoute,
    DashboardCampanhasNovaPontosRoute: DashboardCampanhasNovaPontosRoute,
    DashboardCampanhasNovaRevisaoRoute: DashboardCampanhasNovaRevisaoRoute,
    DashboardCampanhasNovaIndexRoute: DashboardCampanhasNovaIndexRoute,
  }

const DashboardCampanhasNovaRouteWithChildren =
  DashboardCampanhasNovaRoute._addFileChildren(
    DashboardCampanhasNovaRouteChildren,
  )

interface DashboardCampanhasRouteChildren {
  DashboardCampanhasNovaRoute: typeof DashboardCampanhasNovaRouteWithChildren
  DashboardCampanhasIndexRoute: typeof DashboardCampanhasIndexRoute
}

const DashboardCampanhasRouteChildren: DashboardCampanhasRouteChildren = {
  DashboardCampanhasNovaRoute: DashboardCampanhasNovaRouteWithChildren,
  DashboardCampanhasIndexRoute: DashboardCampanhasIndexRoute,
}

const DashboardCampanhasRouteWithChildren =
  DashboardCampanhasRoute._addFileChildren(DashboardCampanhasRouteChildren)

interface DashboardPedidosRouteChildren {
  DashboardPedidosIdRoute: typeof DashboardPedidosIdRoute
  DashboardPedidosIndexRoute: typeof DashboardPedidosIndexRoute
}

const DashboardPedidosRouteChildren: DashboardPedidosRouteChildren = {
  DashboardPedidosIdRoute: DashboardPedidosIdRoute,
  DashboardPedidosIndexRoute: DashboardPedidosIndexRoute,
}

const DashboardPedidosRouteWithChildren =
  DashboardPedidosRoute._addFileChildren(DashboardPedidosRouteChildren)

interface DashboardRouteChildren {
  DashboardCalendarioRoute: typeof DashboardCalendarioRoute
  DashboardCampanhasRoute: typeof DashboardCampanhasRouteWithChildren
  DashboardMidiasRoute: typeof DashboardMidiasRoute
  DashboardPedidosRoute: typeof DashboardPedidosRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCalendarioRoute: DashboardCalendarioRoute,
  DashboardCampanhasRoute: DashboardCampanhasRouteWithChildren,
  DashboardMidiasRoute: DashboardMidiasRoute,
  DashboardPedidosRoute: DashboardPedidosRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContatoRoute: ContatoRoute,
  CriarContaRoute: CriarContaRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EntrarRoute: EntrarRoute,
  GaleriaRoute: GaleriaRoute,
  MidiaRoute: MidiaRoute,
  PlanejadorRoute: PlanejadorRoute,
  RedeRoute: RedeRoute,
  SobreRoute: SobreRoute,
  PontoSlugRoute: PontoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
