/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as RedeRouteImport } from './routes/rede'
import { Route as PlanejadorRouteImport } from './routes/planejador'
import { Route as MidiaRouteImport } from './routes/midia'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as PontoSlugRouteImport } from './routes/ponto.$slug'
import { Route as DashboardPedidosRouteImport } from './routes/dashboard.pedidos'
import { Route as DashboardMidiasRouteImport } from './routes/dashboard.midias'
import { Route as DashboardCampanhasRouteImport } from './routes/dashboard.campanhas'
import { Route as DashboardCalendarioRouteImport } from './routes/dashboard.calendario'
import { Route as DashboardCampanhasIndexRouteImport } from './routes/dashboard.campanhas.index'
import { Route as DashboardCampanhasNovaRouteImport } from './routes/dashboard.campanhas.nova'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeRoute = RedeRouteImport.update({
  id: '/rede',
  path: '/rede',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejadorRoute = PlanejadorRouteImport.update({
  id: '/planejador',
  path: '/planejador',
  getParentRoute: () => rootRouteImport,
} as any)
const MidiaRoute = MidiaRouteImport.update({
  id: '/midia',
  path: '/midia',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PontoSlugRoute = PontoSlugRouteImport.update({
  id: '/ponto/$slug',
  path: '/ponto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPedidosRoute = DashboardPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMidiasRoute = DashboardMidiasRouteImport.update({
  id: '/midias',
  path: '/midias',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampanhasRoute = DashboardCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarioRoute = DashboardCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampanhasIndexRoute = DashboardCampanhasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCampanhasRoute,
} as any)
const DashboardCampanhasNovaRoute = DashboardCampanhasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => DashboardCampanhasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contato': typeof ContatoRoute
  '/criar-conta': typeof CriarContaRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/galeria': typeof GaleriaRoute
  '/midia': typeof MidiaRoute
  '/planejador': typeof PlanejadorRoute
  '/rede': typeof RedeRoute
  '/sobre': typeof SobreRoute
  '/dashboard/calendario': typeof DashboardCalendarioRoute
  '/dashboard/campanhas': typeof DashboardCampanhasRouteWithChildren
  '/dashboard/midias': typeof DashboardMidiasRoute
  '/dashboard/pedidos': typeof DashboardPedidosRoute
  '/ponto/$slug': typeof PontoSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/campanhas/nova': typeof DashboardCampanhasNovaRoute
  '/dashboard/campanhas/': typeof DashboardCampanhasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contato': typeof ContatoRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/galeria': typeof GaleriaRoute
  '/midia': typeof MidiaRoute
  '/planejador': typeof PlanejadorRoute
  '/rede': typeof RedeRoute
  '/sobre': typeof SobreRoute
  '/dashboard/calendario': typeof DashboardCalendarioRoute
  '/dashboard/midias': typeof DashboardMidiasRoute
  '/dashboard/pedidos': typeof DashboardPedidosRoute
  '/ponto/$slug': typeof PontoSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/campanhas/nova': typeof DashboardCampanhasNovaRoute
  '/dashboard/campanhas': typeof DashboardCampanhasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contato': typeof ContatoRoute
  '/criar-conta': typeof CriarContaRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/galeria': typeof GaleriaRoute
  '/midia': typeof MidiaRoute
  '/planejador': typeof PlanejadorRoute
  '/rede': typeof RedeRoute
  '/sobre': typeof SobreRoute
  '/dashboard/calendario': typeof DashboardCalendarioRoute
  '/dashboard/campanhas': typeof DashboardCampanhasRouteWithChildren
  '/dashboard/midias': typeof DashboardMidiasRoute
  '/dashboard/pedidos': typeof DashboardPedidosRoute
  '/ponto/$slug': typeof PontoSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/campanhas/nova': typeof DashboardCampanhasNovaRoute
  '/dashboard/campanhas/': typeof DashboardCampanhasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contato'
    | '/criar-conta'
    | '/dashboard'
    | '/entrar'
    | '/galeria'
    | '/midia'
    | '/planejador'
    | '/rede'
    | '/sobre'
    | '/dashboard/calendario'
    | '/dashboard/campanhas'
    | '/dashboard/midias'
    | '/dashboard/pedidos'
    | '/ponto/$slug'
    | '/dashboard/'
    | '/dashboard/campanhas/nova'
    | '/dashboard/campanhas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contato'
    | '/criar-conta'
    | '/entrar'
    | '/galeria'
    | '/midia'
    | '/planejador'
    | '/rede'
    | '/sobre'
    | '/dashboard/calendario'
    | '/dashboard/midias'
    | '/dashboard/pedidos'
    | '/ponto/$slug'
    | '/dashboard'
    | '/dashboard/campanhas/nova'
    | '/dashboard/campanhas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contato'
    | '/criar-conta'
    | '/dashboard'
    | '/entrar'
    | '/galeria'
    | '/midia'
    | '/planejador'
    | '/rede'
    | '/sobre'
    | '/dashboard/calendario'
    | '/dashboard/campanhas'
    | '/dashboard/midias'
    | '/dashboard/pedidos'
    | '/ponto/$slug'
    | '/dashboard/'
    | '/dashboard/campanhas/nova'
    | '/dashboard/campanhas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContatoRoute: typeof ContatoRoute
  CriarContaRoute: typeof CriarContaRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  GaleriaRoute: typeof GaleriaRoute
  MidiaRoute: typeof MidiaRoute
  PlanejadorRoute: typeof PlanejadorRoute
  RedeRoute: typeof RedeRoute
  SobreRoute: typeof SobreRoute
  PontoSlugRoute: typeof PontoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rede': {
      id: '/rede'
      path: '/rede'
      fullPath: '/rede'
      preLoaderRoute: typeof RedeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejador': {
      id: '/planejador'
      path: '/planejador'
      fullPath: '/planejador'
      preLoaderRoute: typeof PlanejadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midia': {
      id: '/midia'
      path: '/midia'
      fullPath: '/midia'
      preLoaderRoute: typeof MidiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/ponto/$slug': {
      id: '/ponto/$slug'
      path: '/ponto/$slug'
      fullPath: '/ponto/$slug'
      preLoaderRoute: typeof PontoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pedidos': {
      id: '/dashboard/pedidos'
      path: '/pedidos'
      fullPath: '/dashboard/pedidos'
      preLoaderRoute: typeof DashboardPedidosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/midias': {
      id: '/dashboard/midias'
      path: '/midias'
      fullPath: '/dashboard/midias'
      preLoaderRoute: typeof DashboardMidiasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campanhas': {
      id: '/dashboard/campanhas'
      path: '/campanhas'
      fullPath: '/dashboard/campanhas'
      preLoaderRoute: typeof DashboardCampanhasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendario': {
      id: '/dashboard/calendario'
      path: '/calendario'
      fullPath: '/dashboard/calendario'
      preLoaderRoute: typeof DashboardCalendarioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campanhas/': {
      id: '/dashboard/campanhas/'
      path: '/'
      fullPath: '/dashboard/campanhas/'
      preLoaderRoute: typeof DashboardCampanhasIndexRouteImport
      parentRoute: typeof DashboardCampanhasRoute
    }
    '/dashboard/campanhas/nova': {
      id: '/dashboard/campanhas/nova'
      path: '/nova'
      fullPath: '/dashboard/campanhas/nova'
      preLoaderRoute: typeof DashboardCampanhasNovaRouteImport
      parentRoute: typeof DashboardCampanhasRoute
    }
  }
}

interface DashboardCampanhasRouteChildren {
  DashboardCampanhasNovaRoute: typeof DashboardCampanhasNovaRoute
  DashboardCampanhasIndexRoute: typeof DashboardCampanhasIndexRoute
}

const DashboardCampanhasRouteChildren: DashboardCampanhasRouteChildren = {
  DashboardCampanhasNovaRoute: DashboardCampanhasNovaRoute,
  DashboardCampanhasIndexRoute: DashboardCampanhasIndexRoute,
}

const DashboardCampanhasRouteWithChildren =
  DashboardCampanhasRoute._addFileChildren(DashboardCampanhasRouteChildren)

interface DashboardRouteChildren {
  DashboardCalendarioRoute: typeof DashboardCalendarioRoute
  DashboardCampanhasRoute: typeof DashboardCampanhasRouteWithChildren
  DashboardMidiasRoute: typeof DashboardMidiasRoute
  DashboardPedidosRoute: typeof DashboardPedidosRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCalendarioRoute: DashboardCalendarioRoute,
  DashboardCampanhasRoute: DashboardCampanhasRouteWithChildren,
  DashboardMidiasRoute: DashboardMidiasRoute,
  DashboardPedidosRoute: DashboardPedidosRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContatoRoute: ContatoRoute,
  CriarContaRoute: CriarContaRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EntrarRoute: EntrarRoute,
  GaleriaRoute: GaleriaRoute,
  MidiaRoute: MidiaRoute,
  PlanejadorRoute: PlanejadorRoute,
  RedeRoute: RedeRoute,
  SobreRoute: SobreRoute,
  PontoSlugRoute: PontoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
